[package]
name = "corrupt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.13.0"
memmap = "0.7"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
